#!/usr/bin/env bash
set -euo pipefail

# This script configures basic maintenance on the server:
# - installs a logrotate rule for mongod
# - configures systemd-journald limits
# - installs a daily cron job to run apt-get clean and vacuum journal
# - removes old snap revisions
# - ensures a 512MB swapfile exists (creates if missing)

echo "Configuring maintenance (requires sudo)..."

sudo bash -c 'cat > /etc/logrotate.d/mongod <<"EOF"
/var/log/mongodb/*.log {
    daily
    rotate 7
    compress
    missingok
    notifempty
    create 640 mongodb mongodb
    sharedscripts
    postrotate
        systemctl reload mongod > /dev/null 2>&1 || true
    endscript
}
EOF'

echo "Installed /etc/logrotate.d/mongod"

sudo mkdir -p /etc/systemd/journald.conf.d
sudo bash -c 'cat > /etc/systemd/journald.conf.d/99-maintenance.conf <<"EOF"
[Journal]
SystemMaxUse=200M
RuntimeMaxUse=100M
# Keep files no longer than 7 days
MaxFileSec=7day
EOF'

echo "Installed journald drop-in and restarting systemd-journald..."
sudo systemctl restart systemd-journald || true


# Create maintenance script and cron job
sudo tee /usr/local/bin/kasey-maintenance.sh > /dev/null <<'EOF'
#!/usr/bin/env bash
set -e
# basic cleanup tasks
apt-get clean || true
journalctl --vacuum-size=200M || true
# remove disabled snap revisions
if command -v snap >/dev/null 2>&1; then
  snap list --all | awk '/disabled/{print $1, $2}' | while read snapname rev; do
    snap remove --revision="$rev" "$snapname" || true
  done
fi
EOF

sudo chmod +x /usr/local/bin/kasey-maintenance.sh

sudo bash -c 'cat > /etc/cron.d/kasey-maintenance <<"EOF"
# Run daily maintenance at 03:30
30 3 * * * root /usr/local/bin/kasey-maintenance.sh >> /var/log/kasey-maintenance.log 2>&1
EOF'

echo "Installed cron job /etc/cron.d/kasey-maintenance"

# If a logrotate file exists in the repo, install it to /etc/logrotate.d
if [ -f "${HOME}/kasey-creative-canvas/scripts/kasey-maintenance.logrotate" ]; then
  sudo cp "${HOME}/kasey-creative-canvas/scripts/kasey-maintenance.logrotate" /etc/logrotate.d/kasey-maintenance
  echo "Installed /etc/logrotate.d/kasey-maintenance from repo"
fi

# Ensure a modest swapfile exists (512MB)
if ! swapon --show | grep -q '/swapfile' 2>/dev/null; then
  echo "Creating 512MB swapfile at /swapfile"
  sudo fallocate -l 512M /swapfile
  sudo chmod 600 /swapfile
  sudo mkswap /swapfile
  sudo swapon /swapfile
  # Persist
  if ! grep -q '/swapfile' /etc/fstab; then
    echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null
  fi
else
  echo "Swapfile already present"
fi

echo "Maintenance setup complete. Review /var/log/kasey-maintenance.log after first run."


# Install a lightweight healthcheck that restarts services only when unhealthy
# Auto-detect app user and binary locations to avoid hardcoding
# Prefer the SUDO_USER (user who invoked sudo) otherwise fall back to repo owner or 'ubuntu'
REPO_DIR="${HOME}/kasey-creative-canvas"
if [ -d "${REPO_DIR}" ]; then
  REPO_OWNER=$(stat -c %U "${REPO_DIR}")
else
  REPO_OWNER=$(ls -d /home/*/kasey-creative-canvas 2>/dev/null | awk -F/ '{print $3}' | head -n1 || true)
fi
APP_USER=${SUDO_USER:-${REPO_OWNER:-ubuntu}}
APP_HOME=$(runuser -l "${APP_USER}" -c 'echo $HOME' 2>/dev/null || echo "/home/${APP_USER}")

# Resolve binaries or fall back to sensible defaults
MONGOSH_BIN=$(command -v mongosh || echo /usr/bin/mongosh)
CURL_BIN=$(command -v curl || echo /usr/bin/curl)
APP_URL=${APP_URL:-"http://127.0.0.1:3000/painting/"}

sudo tee /usr/local/bin/kasey-healthcheck.sh > /dev/null <<EOF
#!/usr/bin/env bash
set -e
# Healthcheck generated by setup-maintenance.sh — uses detected values
MONGOSH_BIN=${MONGOSH_BIN}
CURL_BIN=${CURL_BIN}
APP_USER=${APP_USER}
APP_HOME=${APP_HOME}
APP_URL="http://127.0.0.1:3000/painting/"

# If Mongo is unresponsive, restart it
if ! ${MONGOSH_BIN} --quiet --eval "db.runCommand({ping:1})" >/dev/null 2>&1; then
  echo "$(date -Iseconds) mongod unresponsive — restarting" >> /var/log/kasey-maintenance.log 2>&1 || true
  systemctl restart mongod || true
fi

# If the local app is not responding, restart pm2-managed apps as the app user
if ! ${CURL_BIN} -fsS "${APP_URL}" >/dev/null 2>&1; then
  echo "$(date -Iseconds) app unresponsive — restarting pm2 (user=${APP_USER})" >> /var/log/kasey-maintenance.log 2>&1 || true
  runuser -l "${APP_USER}" -c "export NVM_DIR=\"${APP_HOME}/.nvm\"; [ -s \"\$NVM_DIR/nvm.sh\" ] && . \"\$NVM_DIR/nvm.sh\"; pm2 restart all" || true
fi
EOF

sudo chmod +x /usr/local/bin/kasey-healthcheck.sh

sudo tee /etc/cron.d/kasey-healthcheck > /dev/null <<'EOF'
# Run healthcheck every 30 minutes
*/30 * * * * root /usr/local/bin/kasey-healthcheck.sh >> /var/log/kasey-healthcheck.log 2>&1
EOF

echo "Installed healthcheck and cron (/etc/cron.d/kasey-healthcheck)"
